/*
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package kubevirt.io;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * DataVolumeSourceRegistry provides the parameters to create a Data Volume from an registry source
 */
@ApiModel(description = "DataVolumeSourceRegistry provides the parameters to create a Data Volume from an registry source")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-11-10T14:44:51.030+02:00")
public class V1alpha1DataVolumeSourceRegistry {
  @SerializedName("certConfigMap")
  private String certConfigMap = null;

  @SerializedName("secretRef")
  private String secretRef = null;

  @SerializedName("url")
  private String url = null;

  public V1alpha1DataVolumeSourceRegistry certConfigMap(String certConfigMap) {
    this.certConfigMap = certConfigMap;
    return this;
  }

   /**
   * CertConfigMap provides a reference to the Registry certs
   * @return certConfigMap
  **/
  @ApiModelProperty(value = "CertConfigMap provides a reference to the Registry certs")
  public String getCertConfigMap() {
    return certConfigMap;
  }

  public void setCertConfigMap(String certConfigMap) {
    this.certConfigMap = certConfigMap;
  }

  public V1alpha1DataVolumeSourceRegistry secretRef(String secretRef) {
    this.secretRef = secretRef;
    return this;
  }

   /**
   * SecretRef provides the secret reference needed to access the Registry source
   * @return secretRef
  **/
  @ApiModelProperty(value = "SecretRef provides the secret reference needed to access the Registry source")
  public String getSecretRef() {
    return secretRef;
  }

  public void setSecretRef(String secretRef) {
    this.secretRef = secretRef;
  }

  public V1alpha1DataVolumeSourceRegistry url(String url) {
    this.url = url;
    return this;
  }

   /**
   * URL is the url of the Registry source
   * @return url
  **/
  @ApiModelProperty(value = "URL is the url of the Registry source")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1DataVolumeSourceRegistry v1alpha1DataVolumeSourceRegistry = (V1alpha1DataVolumeSourceRegistry) o;
    return Objects.equals(this.certConfigMap, v1alpha1DataVolumeSourceRegistry.certConfigMap) &&
        Objects.equals(this.secretRef, v1alpha1DataVolumeSourceRegistry.secretRef) &&
        Objects.equals(this.url, v1alpha1DataVolumeSourceRegistry.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(certConfigMap, secretRef, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1DataVolumeSourceRegistry {\n");
    
    sb.append("    certConfigMap: ").append(toIndentedString(certConfigMap)).append("\n");
    sb.append("    secretRef: ").append(toIndentedString(secretRef)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

