/*
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package kubevirt.io;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import kubevirt.io.V1BIOS;
import kubevirt.io.V1EFI;

/**
 * Represents the firmware blob used to assist in the domain creation process. Used for setting the QEMU BIOS file path for the libvirt domain.
 */
@ApiModel(description = "Represents the firmware blob used to assist in the domain creation process. Used for setting the QEMU BIOS file path for the libvirt domain.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-11-10T14:44:51.030+02:00")
public class V1Bootloader {
  @SerializedName("bios")
  private V1BIOS bios = null;

  @SerializedName("efi")
  private V1EFI efi = null;

  public V1Bootloader bios(V1BIOS bios) {
    this.bios = bios;
    return this;
  }

   /**
   * If set (default), BIOS will be used. +optional
   * @return bios
  **/
  @ApiModelProperty(value = "If set (default), BIOS will be used. +optional")
  public V1BIOS getBios() {
    return bios;
  }

  public void setBios(V1BIOS bios) {
    this.bios = bios;
  }

  public V1Bootloader efi(V1EFI efi) {
    this.efi = efi;
    return this;
  }

   /**
   * If set, EFI will be used instead of BIOS. +optional
   * @return efi
  **/
  @ApiModelProperty(value = "If set, EFI will be used instead of BIOS. +optional")
  public V1EFI getEfi() {
    return efi;
  }

  public void setEfi(V1EFI efi) {
    this.efi = efi;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1Bootloader v1Bootloader = (V1Bootloader) o;
    return Objects.equals(this.bios, v1Bootloader.bios) &&
        Objects.equals(this.efi, v1Bootloader.efi);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bios, efi);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1Bootloader {\n");
    
    sb.append("    bios: ").append(toIndentedString(bios)).append("\n");
    sb.append("    efi: ").append(toIndentedString(efi)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

