/*
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package kubevirt.io;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1CDRomTarget
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-11-10T14:44:51.030+02:00")
public class V1CDRomTarget {
  @SerializedName("bus")
  private String bus = null;

  @SerializedName("readonly")
  private Boolean readonly = null;

  @SerializedName("tray")
  private String tray = null;

  public V1CDRomTarget bus(String bus) {
    this.bus = bus;
    return this;
  }

   /**
   * Bus indicates the type of disk device to emulate. supported values: virtio, sata, scsi.
   * @return bus
  **/
  @ApiModelProperty(value = "Bus indicates the type of disk device to emulate. supported values: virtio, sata, scsi.")
  public String getBus() {
    return bus;
  }

  public void setBus(String bus) {
    this.bus = bus;
  }

  public V1CDRomTarget readonly(Boolean readonly) {
    this.readonly = readonly;
    return this;
  }

   /**
   * ReadOnly. Defaults to true.
   * @return readonly
  **/
  @ApiModelProperty(value = "ReadOnly. Defaults to true.")
  public Boolean isReadonly() {
    return readonly;
  }

  public void setReadonly(Boolean readonly) {
    this.readonly = readonly;
  }

  public V1CDRomTarget tray(String tray) {
    this.tray = tray;
    return this;
  }

   /**
   * Tray indicates if the tray of the device is open or closed. Allowed values are \&quot;open\&quot; and \&quot;closed\&quot;. Defaults to closed. +optional
   * @return tray
  **/
  @ApiModelProperty(value = "Tray indicates if the tray of the device is open or closed. Allowed values are \"open\" and \"closed\". Defaults to closed. +optional")
  public String getTray() {
    return tray;
  }

  public void setTray(String tray) {
    this.tray = tray;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1CDRomTarget v1CDRomTarget = (V1CDRomTarget) o;
    return Objects.equals(this.bus, v1CDRomTarget.bus) &&
        Objects.equals(this.readonly, v1CDRomTarget.readonly) &&
        Objects.equals(this.tray, v1CDRomTarget.tray);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bus, readonly, tray);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1CDRomTarget {\n");
    
    sb.append("    bus: ").append(toIndentedString(bus)).append("\n");
    sb.append("    readonly: ").append(toIndentedString(readonly)).append("\n");
    sb.append("    tray: ").append(toIndentedString(tray)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

