/*
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package kubevirt.io;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1FeatureVendorID
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-11-10T14:44:51.030+02:00")
public class V1FeatureVendorID {
  @SerializedName("enabled")
  private Boolean enabled = null;

  @SerializedName("vendorid")
  private String vendorid = null;

  public V1FeatureVendorID enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Enabled determines if the feature should be enabled or disabled on the guest. Defaults to true. +optional
   * @return enabled
  **/
  @ApiModelProperty(value = "Enabled determines if the feature should be enabled or disabled on the guest. Defaults to true. +optional")
  public Boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  public V1FeatureVendorID vendorid(String vendorid) {
    this.vendorid = vendorid;
    return this;
  }

   /**
   * VendorID sets the hypervisor vendor id, visible to the vmi. String up to twelve characters.
   * @return vendorid
  **/
  @ApiModelProperty(value = "VendorID sets the hypervisor vendor id, visible to the vmi. String up to twelve characters.")
  public String getVendorid() {
    return vendorid;
  }

  public void setVendorid(String vendorid) {
    this.vendorid = vendorid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1FeatureVendorID v1FeatureVendorID = (V1FeatureVendorID) o;
    return Objects.equals(this.enabled, v1FeatureVendorID.enabled) &&
        Objects.equals(this.vendorid, v1FeatureVendorID.vendorid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enabled, vendorid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1FeatureVendorID {\n");
    
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    vendorid: ").append(toIndentedString(vendorid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

