/*
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package kubevirt.io;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import kubevirt.io.V1FeatureAPIC;
import kubevirt.io.V1FeatureHyperv;
import kubevirt.io.V1FeatureState;

/**
 * V1Features
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-11-10T14:44:51.030+02:00")
public class V1Features {
  @SerializedName("acpi")
  private V1FeatureState acpi = null;

  @SerializedName("apic")
  private V1FeatureAPIC apic = null;

  @SerializedName("hyperv")
  private V1FeatureHyperv hyperv = null;

  @SerializedName("smm")
  private V1FeatureState smm = null;

  public V1Features acpi(V1FeatureState acpi) {
    this.acpi = acpi;
    return this;
  }

   /**
   * ACPI enables/disables ACPI insidejsondata guest. Defaults to enabled. +optional
   * @return acpi
  **/
  @ApiModelProperty(value = "ACPI enables/disables ACPI insidejsondata guest. Defaults to enabled. +optional")
  public V1FeatureState getAcpi() {
    return acpi;
  }

  public void setAcpi(V1FeatureState acpi) {
    this.acpi = acpi;
  }

  public V1Features apic(V1FeatureAPIC apic) {
    this.apic = apic;
    return this;
  }

   /**
   * Defaults to the machine type setting. +optional
   * @return apic
  **/
  @ApiModelProperty(value = "Defaults to the machine type setting. +optional")
  public V1FeatureAPIC getApic() {
    return apic;
  }

  public void setApic(V1FeatureAPIC apic) {
    this.apic = apic;
  }

  public V1Features hyperv(V1FeatureHyperv hyperv) {
    this.hyperv = hyperv;
    return this;
  }

   /**
   * Defaults to the machine type setting. +optional
   * @return hyperv
  **/
  @ApiModelProperty(value = "Defaults to the machine type setting. +optional")
  public V1FeatureHyperv getHyperv() {
    return hyperv;
  }

  public void setHyperv(V1FeatureHyperv hyperv) {
    this.hyperv = hyperv;
  }

  public V1Features smm(V1FeatureState smm) {
    this.smm = smm;
    return this;
  }

   /**
   * SMM enables/disables System Management Mode. TSEG not yet implemented. +optional
   * @return smm
  **/
  @ApiModelProperty(value = "SMM enables/disables System Management Mode. TSEG not yet implemented. +optional")
  public V1FeatureState getSmm() {
    return smm;
  }

  public void setSmm(V1FeatureState smm) {
    this.smm = smm;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1Features v1Features = (V1Features) o;
    return Objects.equals(this.acpi, v1Features.acpi) &&
        Objects.equals(this.apic, v1Features.apic) &&
        Objects.equals(this.hyperv, v1Features.hyperv) &&
        Objects.equals(this.smm, v1Features.smm);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acpi, apic, hyperv, smm);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1Features {\n");
    
    sb.append("    acpi: ").append(toIndentedString(acpi)).append("\n");
    sb.append("    apic: ").append(toIndentedString(apic)).append("\n");
    sb.append("    hyperv: ").append(toIndentedString(hyperv)).append("\n");
    sb.append("    smm: ").append(toIndentedString(smm)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

