/*
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package kubevirt.io;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import kubevirt.io.V1Bootloader;

/**
 * V1Firmware
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-11-10T14:44:51.030+02:00")
public class V1Firmware {
  @SerializedName("bootloader")
  private V1Bootloader bootloader = null;

  @SerializedName("serial")
  private String serial = null;

  @SerializedName("uuid")
  private String uuid = null;

  public V1Firmware bootloader(V1Bootloader bootloader) {
    this.bootloader = bootloader;
    return this;
  }

   /**
   * Settings to control the bootloader that is used. +optional
   * @return bootloader
  **/
  @ApiModelProperty(value = "Settings to control the bootloader that is used. +optional")
  public V1Bootloader getBootloader() {
    return bootloader;
  }

  public void setBootloader(V1Bootloader bootloader) {
    this.bootloader = bootloader;
  }

  public V1Firmware serial(String serial) {
    this.serial = serial;
    return this;
  }

   /**
   * The system-serial-number in SMBIOS
   * @return serial
  **/
  @ApiModelProperty(value = "The system-serial-number in SMBIOS")
  public String getSerial() {
    return serial;
  }

  public void setSerial(String serial) {
    this.serial = serial;
  }

  public V1Firmware uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * UUID reported by the vmi bios. Defaults to a random generated uid.
   * @return uuid
  **/
  @ApiModelProperty(value = "UUID reported by the vmi bios. Defaults to a random generated uid.")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1Firmware v1Firmware = (V1Firmware) o;
    return Objects.equals(this.bootloader, v1Firmware.bootloader) &&
        Objects.equals(this.serial, v1Firmware.serial) &&
        Objects.equals(this.uuid, v1Firmware.uuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bootloader, serial, uuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1Firmware {\n");
    
    sb.append("    bootloader: ").append(toIndentedString(bootloader)).append("\n");
    sb.append("    serial: ").append(toIndentedString(serial)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

