/*
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package kubevirt.io;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1FloppyTarget
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-11-10T14:44:51.030+02:00")
public class V1FloppyTarget {
  @SerializedName("readonly")
  private Boolean readonly = null;

  @SerializedName("tray")
  private String tray = null;

  public V1FloppyTarget readonly(Boolean readonly) {
    this.readonly = readonly;
    return this;
  }

   /**
   * ReadOnly. Defaults to false.
   * @return readonly
  **/
  @ApiModelProperty(value = "ReadOnly. Defaults to false.")
  public Boolean isReadonly() {
    return readonly;
  }

  public void setReadonly(Boolean readonly) {
    this.readonly = readonly;
  }

  public V1FloppyTarget tray(String tray) {
    this.tray = tray;
    return this;
  }

   /**
   * Tray indicates if the tray of the device is open or closed. Allowed values are \&quot;open\&quot; and \&quot;closed\&quot;. Defaults to closed. +optional
   * @return tray
  **/
  @ApiModelProperty(value = "Tray indicates if the tray of the device is open or closed. Allowed values are \"open\" and \"closed\". Defaults to closed. +optional")
  public String getTray() {
    return tray;
  }

  public void setTray(String tray) {
    this.tray = tray;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1FloppyTarget v1FloppyTarget = (V1FloppyTarget) o;
    return Objects.equals(this.readonly, v1FloppyTarget.readonly) &&
        Objects.equals(this.tray, v1FloppyTarget.tray);
  }

  @Override
  public int hashCode() {
    return Objects.hash(readonly, tray);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1FloppyTarget {\n");
    
    sb.append("    readonly: ").append(toIndentedString(readonly)).append("\n");
    sb.append("    tray: ").append(toIndentedString(tray)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

