/*
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package kubevirt.io;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Hugepages allow to use hugepages for the VirtualMachineInstance instead of regular memory.
 */
@ApiModel(description = "Hugepages allow to use hugepages for the VirtualMachineInstance instead of regular memory.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-11-10T14:44:51.030+02:00")
public class V1Hugepages {
  @SerializedName("pageSize")
  private String pageSize = null;

  public V1Hugepages pageSize(String pageSize) {
    this.pageSize = pageSize;
    return this;
  }

   /**
   * PageSize specifies the hugepage size, for x86_64 architecture valid values are 1Gi and 2Mi.
   * @return pageSize
  **/
  @ApiModelProperty(value = "PageSize specifies the hugepage size, for x86_64 architecture valid values are 1Gi and 2Mi.")
  public String getPageSize() {
    return pageSize;
  }

  public void setPageSize(String pageSize) {
    this.pageSize = pageSize;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1Hugepages v1Hugepages = (V1Hugepages) o;
    return Objects.equals(this.pageSize, v1Hugepages.pageSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pageSize);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1Hugepages {\n");
    
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

