/*
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package kubevirt.io;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import kubevirt.io.V1GenieNetwork;
import kubevirt.io.V1MultusNetwork;
import kubevirt.io.V1PodNetwork;

/**
 * Network represents a network type and a resource that should be connected to the vm.
 */
@ApiModel(description = "Network represents a network type and a resource that should be connected to the vm.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-11-10T14:44:51.030+02:00")
public class V1Network {
  @SerializedName("genie")
  private V1GenieNetwork genie = null;

  @SerializedName("multus")
  private V1MultusNetwork multus = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("pod")
  private V1PodNetwork pod = null;

  public V1Network genie(V1GenieNetwork genie) {
    this.genie = genie;
    return this;
  }

   /**
   * Get genie
   * @return genie
  **/
  @ApiModelProperty(value = "")
  public V1GenieNetwork getGenie() {
    return genie;
  }

  public void setGenie(V1GenieNetwork genie) {
    this.genie = genie;
  }

  public V1Network multus(V1MultusNetwork multus) {
    this.multus = multus;
    return this;
  }

   /**
   * Get multus
   * @return multus
  **/
  @ApiModelProperty(value = "")
  public V1MultusNetwork getMultus() {
    return multus;
  }

  public void setMultus(V1MultusNetwork multus) {
    this.multus = multus;
  }

  public V1Network name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Network name. Must be a DNS_LABEL and unique within the vm. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Network name. Must be a DNS_LABEL and unique within the vm. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public V1Network pod(V1PodNetwork pod) {
    this.pod = pod;
    return this;
  }

   /**
   * Get pod
   * @return pod
  **/
  @ApiModelProperty(value = "")
  public V1PodNetwork getPod() {
    return pod;
  }

  public void setPod(V1PodNetwork pod) {
    this.pod = pod;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1Network v1Network = (V1Network) o;
    return Objects.equals(this.genie, v1Network.genie) &&
        Objects.equals(this.multus, v1Network.multus) &&
        Objects.equals(this.name, v1Network.name) &&
        Objects.equals(this.pod, v1Network.pod);
  }

  @Override
  public int hashCode() {
    return Objects.hash(genie, multus, name, pod);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1Network {\n");
    
    sb.append("    genie: ").append(toIndentedString(genie)).append("\n");
    sb.append("    multus: ").append(toIndentedString(multus)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    pod: ").append(toIndentedString(pod)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

