/*
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package kubevirt.io;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Represents the stock pod network interface.
 */
@ApiModel(description = "Represents the stock pod network interface.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-11-10T14:44:51.030+02:00")
public class V1PodNetwork {
  @SerializedName("vmNetworkCIDR")
  private String vmNetworkCIDR = null;

  public V1PodNetwork vmNetworkCIDR(String vmNetworkCIDR) {
    this.vmNetworkCIDR = vmNetworkCIDR;
    return this;
  }

   /**
   * CIDR for vm network. Default 10.0.2.0/24 if not specified.
   * @return vmNetworkCIDR
  **/
  @ApiModelProperty(value = "CIDR for vm network. Default 10.0.2.0/24 if not specified.")
  public String getVmNetworkCIDR() {
    return vmNetworkCIDR;
  }

  public void setVmNetworkCIDR(String vmNetworkCIDR) {
    this.vmNetworkCIDR = vmNetworkCIDR;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1PodNetwork v1PodNetwork = (V1PodNetwork) o;
    return Objects.equals(this.vmNetworkCIDR, v1PodNetwork.vmNetworkCIDR);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vmNetworkCIDR);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1PodNetwork {\n");
    
    sb.append("    vmNetworkCIDR: ").append(toIndentedString(vmNetworkCIDR)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

