/*
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package kubevirt.io;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import kubevirt.io.V1VirtualMachineInstanceMigrationCondition;

/**
 * VirtualMachineInstanceMigration reprents information pertaining to a VMI&#39;s migration.
 */
@ApiModel(description = "VirtualMachineInstanceMigration reprents information pertaining to a VMI's migration.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-11-10T14:44:51.030+02:00")
public class V1VirtualMachineInstanceMigrationStatus {
  @SerializedName("conditions")
  private List<V1VirtualMachineInstanceMigrationCondition> conditions = null;

  @SerializedName("phase")
  private String phase = null;

  public V1VirtualMachineInstanceMigrationStatus conditions(List<V1VirtualMachineInstanceMigrationCondition> conditions) {
    this.conditions = conditions;
    return this;
  }

  public V1VirtualMachineInstanceMigrationStatus addConditionsItem(V1VirtualMachineInstanceMigrationCondition conditionsItem) {
    if (this.conditions == null) {
      this.conditions = new ArrayList<>();
    }
    this.conditions.add(conditionsItem);
    return this;
  }

   /**
   * Get conditions
   * @return conditions
  **/
  @ApiModelProperty(value = "")
  public List<V1VirtualMachineInstanceMigrationCondition> getConditions() {
    return conditions;
  }

  public void setConditions(List<V1VirtualMachineInstanceMigrationCondition> conditions) {
    this.conditions = conditions;
  }

  public V1VirtualMachineInstanceMigrationStatus phase(String phase) {
    this.phase = phase;
    return this;
  }

   /**
   * Get phase
   * @return phase
  **/
  @ApiModelProperty(value = "")
  public String getPhase() {
    return phase;
  }

  public void setPhase(String phase) {
    this.phase = phase;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1VirtualMachineInstanceMigrationStatus v1VirtualMachineInstanceMigrationStatus = (V1VirtualMachineInstanceMigrationStatus) o;
    return Objects.equals(this.conditions, v1VirtualMachineInstanceMigrationStatus.conditions) &&
        Objects.equals(this.phase, v1VirtualMachineInstanceMigrationStatus.phase);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conditions, phase);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1VirtualMachineInstanceMigrationStatus {\n");
    
    sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
    sb.append("    phase: ").append(toIndentedString(phase)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

