/*
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package kubevirt.io;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1VirtualMachineInstanceGuestOSInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-11-10T14:44:51.030+02:00")
public class V1VirtualMachineInstanceGuestOSInfo {
  @SerializedName("id")
  private String id = null;

  @SerializedName("kernelRelease")
  private String kernelRelease = null;

  @SerializedName("kernelVersion")
  private String kernelVersion = null;

  @SerializedName("machine")
  private String machine = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("prettyName")
  private String prettyName = null;

  @SerializedName("version")
  private String version = null;

  @SerializedName("versionId")
  private String versionId = null;

  public V1VirtualMachineInstanceGuestOSInfo id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Guest OS Id
   * @return id
  **/
  @ApiModelProperty(value = "Guest OS Id")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public V1VirtualMachineInstanceGuestOSInfo kernelRelease(String kernelRelease) {
    this.kernelRelease = kernelRelease;
    return this;
  }

   /**
   * Guest OS Kernel Release
   * @return kernelRelease
  **/
  @ApiModelProperty(value = "Guest OS Kernel Release")
  public String getKernelRelease() {
    return kernelRelease;
  }

  public void setKernelRelease(String kernelRelease) {
    this.kernelRelease = kernelRelease;
  }

  public V1VirtualMachineInstanceGuestOSInfo kernelVersion(String kernelVersion) {
    this.kernelVersion = kernelVersion;
    return this;
  }

   /**
   * Kernel version of the Guest OS
   * @return kernelVersion
  **/
  @ApiModelProperty(value = "Kernel version of the Guest OS")
  public String getKernelVersion() {
    return kernelVersion;
  }

  public void setKernelVersion(String kernelVersion) {
    this.kernelVersion = kernelVersion;
  }

  public V1VirtualMachineInstanceGuestOSInfo machine(String machine) {
    this.machine = machine;
    return this;
  }

   /**
   * Machine type of the Guest OS
   * @return machine
  **/
  @ApiModelProperty(value = "Machine type of the Guest OS")
  public String getMachine() {
    return machine;
  }

  public void setMachine(String machine) {
    this.machine = machine;
  }

  public V1VirtualMachineInstanceGuestOSInfo name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the Guest OS
   * @return name
  **/
  @ApiModelProperty(value = "Name of the Guest OS")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public V1VirtualMachineInstanceGuestOSInfo prettyName(String prettyName) {
    this.prettyName = prettyName;
    return this;
  }

   /**
   * Guest OS Pretty Name
   * @return prettyName
  **/
  @ApiModelProperty(value = "Guest OS Pretty Name")
  public String getPrettyName() {
    return prettyName;
  }

  public void setPrettyName(String prettyName) {
    this.prettyName = prettyName;
  }

  public V1VirtualMachineInstanceGuestOSInfo version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Guest OS Version
   * @return version
  **/
  @ApiModelProperty(value = "Guest OS Version")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public V1VirtualMachineInstanceGuestOSInfo versionId(String versionId) {
    this.versionId = versionId;
    return this;
  }

   /**
   * Version ID of the Guest OS
   * @return versionId
  **/
  @ApiModelProperty(value = "Version ID of the Guest OS")
  public String getVersionId() {
    return versionId;
  }

  public void setVersionId(String versionId) {
    this.versionId = versionId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1VirtualMachineInstanceGuestOSInfo v1VirtualMachineInstanceGuestOSInfo = (V1VirtualMachineInstanceGuestOSInfo) o;
    return Objects.equals(this.id, v1VirtualMachineInstanceGuestOSInfo.id) &&
        Objects.equals(this.kernelRelease, v1VirtualMachineInstanceGuestOSInfo.kernelRelease) &&
        Objects.equals(this.kernelVersion, v1VirtualMachineInstanceGuestOSInfo.kernelVersion) &&
        Objects.equals(this.machine, v1VirtualMachineInstanceGuestOSInfo.machine) &&
        Objects.equals(this.name, v1VirtualMachineInstanceGuestOSInfo.name) &&
        Objects.equals(this.prettyName, v1VirtualMachineInstanceGuestOSInfo.prettyName) &&
        Objects.equals(this.version, v1VirtualMachineInstanceGuestOSInfo.version) &&
        Objects.equals(this.versionId, v1VirtualMachineInstanceGuestOSInfo.versionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, kernelRelease, kernelVersion, machine, name, prettyName, version, versionId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1VirtualMachineInstanceGuestOSInfo {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    kernelRelease: ").append(toIndentedString(kernelRelease)).append("\n");
    sb.append("    kernelVersion: ").append(toIndentedString(kernelVersion)).append("\n");
    sb.append("    machine: ").append(toIndentedString(machine)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    prettyName: ").append(toIndentedString(prettyName)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    versionId: ").append(toIndentedString(versionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

