/*
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package kubevirt.io;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import kubevirt.io.TypesUID;

/**
 * V1VirtualMachineStateChangeRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-11-10T14:44:51.030+02:00")
public class V1VirtualMachineStateChangeRequest {
  @SerializedName("action")
  private String action = null;

  @SerializedName("uid")
  private TypesUID uid = null;

  public V1VirtualMachineStateChangeRequest action(String action) {
    this.action = action;
    return this;
  }

   /**
   * Indicates the type of action that is requested. e.g. Start or Stop
   * @return action
  **/
  @ApiModelProperty(required = true, value = "Indicates the type of action that is requested. e.g. Start or Stop")
  public String getAction() {
    return action;
  }

  public void setAction(String action) {
    this.action = action;
  }

  public V1VirtualMachineStateChangeRequest uid(TypesUID uid) {
    this.uid = uid;
    return this;
  }

   /**
   * Indicates the UUID of an existing Virtual Machine Instance that this change request applies to -- if applicable
   * @return uid
  **/
  @ApiModelProperty(value = "Indicates the UUID of an existing Virtual Machine Instance that this change request applies to -- if applicable")
  public TypesUID getUid() {
    return uid;
  }

  public void setUid(TypesUID uid) {
    this.uid = uid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1VirtualMachineStateChangeRequest v1VirtualMachineStateChangeRequest = (V1VirtualMachineStateChangeRequest) o;
    return Objects.equals(this.action, v1VirtualMachineStateChangeRequest.action) &&
        Objects.equals(this.uid, v1VirtualMachineStateChangeRequest.uid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, uid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1VirtualMachineStateChangeRequest {\n");
    
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

