/*
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package kubevirt.io;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import kubevirt.io.V1LabelSelector;
import kubevirt.io.V1VirtualMachineInstanceTemplateSpec;

/**
 * V1VirtualMachineInstanceReplicaSetSpec
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-11-10T14:44:51.030+02:00")
public class V1VirtualMachineInstanceReplicaSetSpec {
  @SerializedName("paused")
  private Boolean paused = null;

  @SerializedName("replicas")
  private Integer replicas = null;

  @SerializedName("selector")
  private V1LabelSelector selector = null;

  @SerializedName("template")
  private V1VirtualMachineInstanceTemplateSpec template = null;

  public V1VirtualMachineInstanceReplicaSetSpec paused(Boolean paused) {
    this.paused = paused;
    return this;
  }

   /**
   * Indicates that the replica set is paused. +optional
   * @return paused
  **/
  @ApiModelProperty(value = "Indicates that the replica set is paused. +optional")
  public Boolean isPaused() {
    return paused;
  }

  public void setPaused(Boolean paused) {
    this.paused = paused;
  }

  public V1VirtualMachineInstanceReplicaSetSpec replicas(Integer replicas) {
    this.replicas = replicas;
    return this;
  }

   /**
   * Number of desired pods. This is a pointer to distinguish between explicit zero and not specified. Defaults to 1. +optional
   * @return replicas
  **/
  @ApiModelProperty(value = "Number of desired pods. This is a pointer to distinguish between explicit zero and not specified. Defaults to 1. +optional")
  public Integer getReplicas() {
    return replicas;
  }

  public void setReplicas(Integer replicas) {
    this.replicas = replicas;
  }

  public V1VirtualMachineInstanceReplicaSetSpec selector(V1LabelSelector selector) {
    this.selector = selector;
    return this;
  }

   /**
   * Label selector for pods. Existing ReplicaSets whose pods are selected by this will be the ones affected by this deployment.
   * @return selector
  **/
  @ApiModelProperty(required = true, value = "Label selector for pods. Existing ReplicaSets whose pods are selected by this will be the ones affected by this deployment.")
  public V1LabelSelector getSelector() {
    return selector;
  }

  public void setSelector(V1LabelSelector selector) {
    this.selector = selector;
  }

  public V1VirtualMachineInstanceReplicaSetSpec template(V1VirtualMachineInstanceTemplateSpec template) {
    this.template = template;
    return this;
  }

   /**
   * Template describes the pods that will be created.
   * @return template
  **/
  @ApiModelProperty(required = true, value = "Template describes the pods that will be created.")
  public V1VirtualMachineInstanceTemplateSpec getTemplate() {
    return template;
  }

  public void setTemplate(V1VirtualMachineInstanceTemplateSpec template) {
    this.template = template;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1VirtualMachineInstanceReplicaSetSpec v1VirtualMachineInstanceReplicaSetSpec = (V1VirtualMachineInstanceReplicaSetSpec) o;
    return Objects.equals(this.paused, v1VirtualMachineInstanceReplicaSetSpec.paused) &&
        Objects.equals(this.replicas, v1VirtualMachineInstanceReplicaSetSpec.replicas) &&
        Objects.equals(this.selector, v1VirtualMachineInstanceReplicaSetSpec.selector) &&
        Objects.equals(this.template, v1VirtualMachineInstanceReplicaSetSpec.template);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paused, replicas, selector, template);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1VirtualMachineInstanceReplicaSetSpec {\n");
    
    sb.append("    paused: ").append(toIndentedString(paused)).append("\n");
    sb.append("    replicas: ").append(toIndentedString(replicas)).append("\n");
    sb.append("    selector: ").append(toIndentedString(selector)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

