name: build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: centos-stream-8
            shortcut: cs8
            container-name: el8stream
          - name: centos-stream-9
            shortcut: cs9
            container-name: el9stream

    name: ${{ matrix.name }}

    env:
      ARTIFACTS_DIR: exported-artifacts

    container:
      image: quay.io/ovirt/buildcontainer:${{ matrix.container-name }}

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Perform build
      run: |
        .automation/build-rpm.sh $ARTIFACTS_DIR

    - name: Upload artifacts
      uses: ovirt/upload-rpms-action@v2
      with:
        directory: exported-artifacts/
